language: ruby
branches:
  only:
    - master
rvm:
  - 2.7.1
cache:
  bundler: true
  directories:
    - /home/travis/.rvm
before_install:
  - gem install bundler
before_script:
  - sudo apt-get -y install pngquant
  - chmod +x ./deploy.sh
script: ./deploy.sh
